# Generated by Django 3.1.4 on 2021-01-14 03:55

from django.db import migrations, models
from datetime import datetime
now = datetime.now()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=now)),
                ('created_at', models.DateTimeField(db_default=now)),
            ],
        ),
    ]
